# -*- coding: utf-8 -*-
"""day19upi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eAWv7XEPX2jtW0oqIWoux6yaqNMHscdt
"""

!apt-get update && apt-get install -y espeak-ng
!pip install pyttsx3 gTTS
# Linux offline TTS engine: `sudo apt-get install espeak-ng` if needed

from __future__ import annotations

import argparse
import csv
import os
import platform
import random
import shutil
import subprocess
import sys # Added import for sys
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum

AUDIO_DIR = "static/audio"
CSV_PATH = "data/transactions.csv"
CSV_FIELDS = ["txn_id", "timestamp", "txn_type", "amount", "payer_name",
              "payee_name", "vpa", "note", "audio_file"]
DEMO_NAMES = ["Ramesh Kumar", "Priya Sharma", "Amit Traders", "Sneha Patel", "Kirana Store"]


# --------------------------------------------------------------------------- #
# Transaction model
# --------------------------------------------------------------------------- #
class TransactionType(str, Enum):
    CREDIT = "credit"   # money received
    DEBIT = "debit"     # money sent / paid


@dataclass
class UPITransaction:
    amount: float
    txn_type: TransactionType
    payer_name: str = "Unknown"
    payee_name: str = "Unknown"
    vpa: str = ""
    txn_id: str = field(default_factory=lambda: f"UPI{uuid.uuid4().hex[:12].upper()}")
    timestamp: datetime = field(default_factory=datetime.now)
    note: str = ""

    def __post_init__(self):
        if isinstance(self.txn_type, str):
            self.txn_type = TransactionType(self.txn_type.lower())
        if self.amount <= 0:
            raise ValueError("Transaction amount must be greater than zero")

    @property
    def counterparty(self) -> str:
        return self.payer_name if self.txn_type == TransactionType.CREDIT else self.payee_name

    def to_dict(self) -> dict:
        return {
            "txn_id": self.txn_id,
            "amount": self.amount,
            "txn_type": self.txn_type.value,
            "payer_name": self.payer_name,
            "payee_name": self.payee_name,
            "vpa": self.vpa,
            "timestamp": self.timestamp.isoformat(timespec="seconds"),
            "note": self.note,
        }


# --------------------------------------------------------------------------- #
# Message builder
# --------------------------------------------------------------------------- #
def _format_amount_words(amount: float) -> str:
    rupees = int(amount)
    paise = round((amount - rupees) * 100)
    if paise:
        return f"{rupees} rupees and {paise} paise"
    return f"{rupees} rupees"


def build_message(txn: UPITransaction, language: str = "en") -> str:
    amount_words = _format_amount_words(txn.amount)
    who = txn.counterparty

    if txn.txn_type == TransactionType.CREDIT:
        return (f"{amount_words} prapt hue, {who} se."
                if language == "hi" else f"Received {amount_words} from {who}.")
    return (f"{amount_words} bheje gaye, {who} ko."
            if language == "hi" else f"Paid {amount_words} to {who}.")


# --------------------------------------------------------------------------- #
# Text-to-speech
# --------------------------------------------------------------------------- #
class AudioGenerationError(Exception):
    pass


def generate_with_pyttsx3(text: str, out_path: str, rate: int = 165, volume: float = 1.0) -> str:
    import pyttsx3

    engine = pyttsx3.init()
    engine.setProperty("rate", rate)
    engine.setProperty("volume", volume)
    engine.save_to_file(text, out_path)
    engine.runAndWait()
    engine.stop()
    if not os.path.exists(out_path) or os.path.getsize(out_path) == 0:
        raise AudioGenerationError("pyttsx3 failed to write an audio file")
    return out_path


def generate_with_gtts(text: str, out_path: str, lang: str = "en") -> str:
    from gtts import gTTS

    tts = gTTS(text=text, lang=lang)
    tts.save(out_path)
    if not os.path.exists(out_path) or os.path.getsize(out_path) == 0:
        raise AudioGenerationError("gTTS failed to write an audio file")
    return out_path


def generate_audio(text: str, out_path: str, engine: str = "pyttsx3", lang: str = "en") -> str:
    if engine == "gtts":
        try:
            return generate_with_gtts(text, out_path, lang=lang)
        except Exception as exc:
            print(f"[audio] gTTS unavailable ({exc}); falling back to pyttsx3.")
            engine = "pyttsx3"

    if engine == "pyttsx3":
        base, _ext = os.path.splitext(out_path)
        wav_path = base + ".wav"
        return generate_with_pyttsx3(text, wav_path)

    raise ValueError(f"Unknown TTS engine: {engine}")


# --------------------------------------------------------------------------- #
# Playback
# --------------------------------------------------------------------------- #
def play_audio(path: str) -> bool:
    system = platform.system()
    try:
        if system == "Darwin":
            subprocess.run(["afplay", path], check=True)
            return True
        if system == "Windows":
            import winsound  # type: ignore
            winsound.PlaySound(path, winsound.SND_FILENAME)
            return True
        for player in ("paplay", "aplay", "ffplay", "mpg123"):
            if shutil.which(player):
                cmd = [player, path]
                if player == "ffplay":
                    cmd = ["ffplay", "-nodisp", "-autoexit", "-loglevel", "quiet", path]
                subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                return True
        print(f"[player] No audio player found. File saved at: {path}")
        return False
    except Exception as exc:
        print(f"[player] Could not play audio ({exc}). File saved at: {path}")
        return False


# --------------------------------------------------------------------------- #
# CSV ledger
# --------------------------------------------------------------------------- #
def log_transaction(txn: UPITransaction, audio_file: str, csv_path: str = CSV_PATH) -> None:
    os.makedirs(os.path.dirname(csv_path) or ".", exist_ok=True)
    file_exists = os.path.exists(csv_path)
    row = txn.to_dict()
    row["audio_file"] = audio_file
    with open(csv_path, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        if not file_exists:
            writer.writeheader()
        writer.writerow(row)


# --------------------------------------------------------------------------- #
# Orchestrator
# --------------------------------------------------------------------------- #
def announce_transaction(txn: UPITransaction, engine: str = "pyttsx3", language: str = "en",
                          play: bool = True, csv_path: str = CSV_PATH) -> str:
    os.makedirs(AUDIO_DIR, exist_ok=True)
    message = build_message(txn, language=language)
    out_path = os.path.join(AUDIO_DIR, f"{txn.txn_id}.mp3")
    audio_file = generate_audio(message, out_path, engine=engine, lang=language)

    print(f"[notifier] {txn.txn_type.value.upper()}  Rs {txn.amount:,.2f}  "
          f"({txn.counterparty})  ->  \"{message}\"")
    print(f"[notifier] audio saved: {audio_file}")

    if play:
        play_audio(audio_file)
    log_transaction(txn, audio_file, csv_path=csv_path)
    return audio_file


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def make_transaction(amount, txn_type, name, vpa, note):
    if txn_type == "credit":
        return UPITransaction(amount=amount, txn_type=TransactionType.CREDIT,
                               payer_name=name, vpa=vpa, note=note)
    return UPITransaction(amount=amount, txn_type=TransactionType.DEBIT,
                           payee_name=name, vpa=vpa, note=note)


def run_interactive(engine, lang, play):
    print("Interactive mode. Press Ctrl+C to quit.\n")
    while True:
        try:
            amount = float(input("Amount (INR): ").strip())
            txn_type = input("Type [credit/debit] (default credit): ").strip().lower() or "credit"
            name = input("Other party name: ").strip() or "Unknown"
            vpa = input("VPA (optional): ").strip()
            txn = make_transaction(amount, txn_type, name, vpa, "")
            announce_transaction(txn, engine=engine, language=lang, play=play)
            print()
        except KeyboardInterrupt:
            print("\nGoodbye!")
            break
        except ValueError as exc:
            print(f"Invalid input: {exc}\n")


def run_demo(engine, lang, play):
    print("Running demo with 4 simulated transactions...\n")
    for _ in range(4):
        amount = round(random.uniform(20, 5000), 2)
        txn_type = random.choice(["credit", "debit"])
        name = random.choice(DEMO_NAMES)
        txn = make_transaction(amount, txn_type, name, "", "")
        announce_transaction(txn, engine=engine, language=lang, play=play)
        time.sleep(0.5)
        print()


def parse_args():
    p = argparse.ArgumentParser(description="UPI Transaction Audio Notifier")
    p.add_argument("--amount", type=float, help="Transaction amount in INR")
    p.add_argument("--type", choices=["credit", "debit"], default="credit")
    p.add_argument("--name", default="Unknown", help="Name of the other party")
    p.add_argument("--vpa", default="", help="UPI VPA, e.g. name@okaxis")
    p.add_argument("--note", default="")
    p.add_argument("--engine", choices=["pyttsx3", "gtts"], default="pyttsx3")
    p.add_argument("--lang", choices=["en", "hi"], default="en")
    p.add_argument("--no-play", action="store_true")
    p.add_argument("--interactive", action="store_true")
    p.add_argument("--demo", action="store_true")

    # In Jupyter/Colab, sys.argv will contain elements like '-f' which argparse doesn't recognize.
    # We use parse_known_args to ignore these.
    args, unknown = p.parse_known_args()
    return args


def main():
    args = parse_args()
    play = not args.no_play

    if args.demo:
        run_demo(args.engine, args.lang, play)
    elif args.interactive:
        run_interactive(args.engine, args.lang, play)
    elif args.amount is not None:
        txn = make_transaction(args.amount, args.type, args.name, args.vpa, args.note)
        announce_transaction(txn, engine=args.engine, language=args.lang, play=play)
    else:
        # Modified to call run_demo if no specific arguments are provided for a quick demo
        print("No specific arguments provided. Running a demo.")
        run_demo(args.engine, args.lang, play)


if __name__ == "__main__":
    main()

import pandas as pd
import matplotlib.pyplot as plt

# Load the transaction data
df_transactions = pd.read_csv(CSV_PATH)

# Convert 'timestamp' to datetime and set it as the index
df_transactions['timestamp'] = pd.to_datetime(df_transactions['timestamp'])
df_transactions = df_transactions.set_index('timestamp')

# Resample the data to get daily transaction amounts
daily_amounts = df_transactions['amount'].resample('D').sum().fillna(0)

# Create the plot
plt.figure(figsize=(12, 6))
plt.plot(daily_amounts.index, daily_amounts.values, marker='o', linestyle='-')
plt.title('Daily Transaction Amounts Over Time')
plt.xlabel('Date')
plt.ylabel('Total Amount (INR)')
plt.grid(True)
plt.tight_layout()
plt.show()

"""This plot shows the total transaction amounts on a daily basis. You can observe any trends or significant fluctuations in your transaction activity over the recorded period."""