# -*- coding: utf-8 -*-
"""DAY17pollutioncleaning agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1agPAwdtWncXoLdDnCbfynqLpBYNTzG0J
"""

import random

class pollutiongrid:
    def __init__(self, rows=10, cols=10, pollution_ratio=0.15,
                 obstacle_ratio=0.08, seed=None, start=(0,0)):
        self.rows = rows
        self.cols = cols
        self.start = start
        if seed is not None:
            random.seed(seed)
        self.grid = [[0 for _ in range(cols)] for _ in range(rows)]
        self._populate(pollution_ratio, obstacle_ratio)
        # Corrected: Iterate through self.grid to count polluted cells
        self.total_polluted = sum(row.count(1) for row in self.grid)
        self.cleaned_count = 0

    def _populate(self, pollution_ratio, obstacle_ratio):
        cells = [(r,c) for r in range(self.rows) for c in range(self.cols) if (r,c) != self.start]
        random.shuffle(cells)
        n_obstacles = int(len(cells) * obstacle_ratio)
        n_pollution = int(len(cells) * pollution_ratio)
        obstacle_cells = cells[:n_obstacles]
        pollution_cells = cells[n_obstacles:n_obstacles+n_pollution]

        for (r,c) in obstacle_cells:
            self.grid[r][c] = -1
        for (r,c) in pollution_cells: # Corrected indentation
            self.grid[r][c] = 1

    def in_bounds(self, pos):
        r,c = pos
        return 0 <= r < self.rows and 0 <= c < self.cols

    def is_walkable(self, pos):
        r,c = pos
        return self.grid[r][c] != -1

    def is_polluted(self, pos):
        r,c = pos
        return self.grid[r][c] == 1

    def clean(self, pos):
        r,c = pos
        if self.grid[r][c] == 1:
            self.grid[r][c] = 0 # Corrected: Assignment operator
            self.cleaned_count += 1
            return True
        return False

    def polluted_cells(self):
        return [(r,c) for r in range(self.rows) for c in range(self.cols) if self.grid[r][c] == 1]

    def is_fully_clean(self):
        return self.cleaned_count >= self.total_polluted

    def neighbors(self, pos):
        r,c = pos
        candidates = [(r-1,c), (r+1,c), (r,c-1), (r,c+1)]
        return [p for p in candidates if self.in_bounds(p) and self.is_walkable(p)]

from typing import Deque
from os import path
from collections import deque # Fixed: SyntaxError here
import heapq

def bfs_path(env, start, goal):
    if start == goal:
        return [start]

    visited = {start}
    queue = deque([(start, [start])])

    while queue:
        current, path = queue.popleft()
        for nxt in env.neighbors(current): # Fixed: neighbours -> neighbors
            if nxt in visited:
                continue
            new_path = path + [nxt]
            if nxt == goal:
                return new_path
            visited.add(nxt)
            queue.append((nxt, new_path))

    return None

def astar_path(env, start, goal):
    def h(pos):
        return abs(pos[0] - goal[0]) + abs(pos[1] - goal[1])

    open_set = [(h(start), 0, start, [start])]
    best_cost = {start: 0}

    while open_set:
        _, cost, current, path = heapq.heappop(open_set)

        if current == goal:
            return path

        for nxt in env.neighbors(current): # Fixed: neighbours -> neighbors
            new_cost = cost + 1
            if nxt not in best_cost or new_cost < best_cost[nxt]:
                best_cost[nxt] = new_cost
                heapq.heappush(open_set, (new_cost + h(nxt), new_cost, nxt, path + [nxt]))

    return None

def find_nearest_polluted(env, start):
    if env.is_polluted(start):
        return start, [start]

    visited = {start}
    queue = deque([(start, [start])]) # Fixed: Deque -> deque

    while queue:
        current, path = queue.popleft()
        for nxt in env.neighbors(current):
            if nxt in visited:
                continue
            new_path = path + [nxt]
            if env.is_polluted(nxt):
                return nxt, new_path
            visited.add(nxt)
            queue.append((nxt, new_path))

    return None, None

class cleaningagent:
    def __init__(self, env, start=None):
        self.env = env
        self.pos = start if start is not None else env.start
        self.path_history = [self.pos]
        self.clean_events = []
        self.moves = 0

    def run(self, max_iterations=1000):
        iteration = 0
        while not self.env.is_fully_clean() and iteration < max_iterations: # Fixed: max_iteration -> max_iterations
            target, path = find_nearest_polluted(self.env, self.pos)
            if target is None:
                break

            for step in path[1:]:
                self.pos = step
                self.path_history.append(self.pos)
                self.moves += 1
                # Clean the cell after moving to it
                if self.env.is_polluted(self.pos):
                    self.env.clean(self.pos)
                    self.clean_events.append(len(self.path_history) - 1)

            iteration += 1
        return self.env.is_fully_clean()

from IPython.core.completer import position_to_cursor
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import matplotlib.patches as mpatches
import numpy as np

def animate_cleaning(original_grid, path_history, clean_events, rows, cols, save_path="pollution_cleaning.gif", fps=6):
  clean_events = set(clean_events)
  state = [row[:] for row in original_grid]
  fig, ax = plt.subplots(figsize=(6,6)) # Fixed: plt.subploat -> plt.subplots

  cmap_colors = {
      -1:"#2b2b2b",
      0:"#ffffff",
      1:"#e63946",
      2:"#8fd19e"
  }

  def state_to_rgb(state_matrix):
    img = np.zeros((rows, cols, 3)) # Fixed: np.zeroes -> np.zeros
    for r_idx in range(rows):
      for c_idx in range(cols):
        hex_color = cmap_colors[state_matrix[r_idx][c_idx]] # Fixed: state[r][c] -> state_matrix[r_idx][c_idx]
        rgb = tuple(int(hex_color[i:i+2], 16) / 255 for i in (1,3,5))
        img[r_idx, c_idx] = rgb
    return img

  im = ax.imshow(state_to_rgb(state), interpolation="nearest")
  agent_dot, = ax.plot([], [], marker="o", markersize=16, markerfacecolor="#1d3557", markeredgecolor="white", markeredgewidth=2, linestyle="None")
  ax.set_xticks(np.arange(-0.5, cols, 1), minor=True) # Fixed: np.arrange -> np.arange
  ax.grid(which="minor", color="#cccccc", linewidth=0.5)
  ax.set_xticks([])
  ax.set_yticks([])
  ax.set_title("Pollution Cleaning Agent (BFS Search)")
  legend_handles = [
      mpatches.Patch(color=cmap_colors[1], label="Polluted"), # Added comma
      mpatches.Patch(color=cmap_colors[2], label="Cleaned"), # Added comma
      mpatches.Patch(color=cmap_colors[-1], label="Obstacle"), # Added comma
      mpatches.Patch(color="#1d3557", label="Agent")
  ]
  ax.legend(handles=legend_handles, loc="upper center", # Fixed: ax.legendd -> ax.legend
  bbox_to_anchor=(0.5,-0.02), ncol=4, frameon=False, fontsize=8)

  def updates(frame_idx):
    pos = path_history[frame_idx]
    r,c = pos
    if frame_idx in clean_events:
      state[r][c] = 2
    im.set_data(state_to_rgb(state))
    agent_dot.set_data([c],[r])
    return im,agent_dot

  anim = animation.FuncAnimation(fig, updates, frames=len(path_history), interval=1000/fps, blit=False) # Fixed: update -> updates
  writer = animation.PillowWriter(fps=fps)
  anim.save(save_path, writer=writer)
  plt.close(fig)
  return save_path

def plot_static_summary(original_grid, final_grid, rows, cols, save_path="summary.png"):
  cmap_colors = {-1:"#2b2b2b", 0:"#ffffff", 1:"#e63946", 2:"#8fd19e"}

  def to_rgb (grid, mark_cleaned=False, original=None):
    img = np.zeros((rows, cols, 3)) # Fixed: np.zeroes -> np.zeros
    for r_idx in range(rows):
      for c_idx in range(cols):
        val = grid[r_idx][c_idx] # Fixed: grid[r][c] -> grid[r_idx][c_idx]
        if mark_cleaned and original is not None and original[r_idx][c_idx] == 1 and val == 0:
          val = 2
        hex_color = cmap_colors[val]
        rgb = tuple(int(hex_color[i:i+2],16)/255 for i in (1,3,5))
        img[r_idx,c_idx] = rgb
    return img

  fig, axes = plt.subplots(1, 2, figsize=(10,5)) # Fixed: plt.subploat -> plt.subplots
  axes[0].imshow(to_rgb(original_grid))
  axes[0].set_title("Before Cleaning")
  axes[0].set_xticks([]);axes[0].set_yticks([])
  axes[1].imshow(to_rgb(final_grid, mark_cleaned=True, original=original_grid)) # Fixed: marks_cleaned -> mark_cleaned
  axes[1].set_title("After Cleaning")
  axes[1].set_xticks([]);axes[1].set_yticks([])
  plt.tight_layout()
  plt.savefig(save_path,dpi=150)
  plt.close(fig)
  return save_path

import copy
# The classes/functions are already defined in previous cells and are in the global namespace.
# from environment import pollutiongrid
# from agent import cleaningagent
# from visualize import animate_cleaning,plot_static_summary
rows=10
cols=10
pollution_ratio=0.15
obstacle_ratio=0.08
seed=42
start_pos=(0,0)
gif_path="pollution_cleaning.gif"
summary_path="summary.png"
fps=6
def main():
  env=pollutiongrid(
      rows=rows,cols=cols,pollution_ratio=pollution_ratio,obstacle_ratio=obstacle_ratio,seed=seed,
      start=start_pos
  )
  original_grid=copy.deepcopy(env.grid)
  total_pollution=env.total_polluted
  print(f"grid size:{rows}x{cols}")
  print(f"polluted cell at start:{total_pollution}")
  print(f"obstacles:{sum(row.count(-1) for row in env.grid )}")
  print(f"agent start position:{start_pos}\n")
  agent=cleaningagent(env,start=start_pos)
  fully_cleaned=agent.run()
  print("==run summary==")
  print(f"cells cleaned:{env.cleaned_count}/{total_pollution}")
  print(f"total moves taken:{agent.moves}")
  print(f"all pollution cleaned:{fully_cleaned}")
  if not fully_cleaned:
    remaining=env.polluted_cells()
    print(f"remaning cell:{remaining}")
  print("\ngenerate animation")
  animate_cleaning(
      original_grid=original_grid,
      path_history=agent.path_history,
      clean_events=agent.clean_events,
      rows=rows,cols=cols,
      save_path=gif_path,fps=fps
  )
  print(f"saved animation:{gif_path}")
  plot_static_summary(
      original_grid=original_grid,
      final_grid=env.grid,
      rows=rows,cols=cols,
      save_path=summary_path
  )
  print(f"saved before snapshot to :{summary_path}")
if __name__=="__main__":
  main()

from IPython.display import Image
Image(filename='pollution_cleaning.gif')

