# -*- coding: utf-8 -*-
"""day25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJbXEpCVkmfT3QQEqOfPPlarIRYlwQAg

Day 23 Project (Real Dataset Version) — Classification with Logistic Regression vs. KNN
--------------------------------------------------------------
Works with ANY classification CSV (e.g. Telco Customer Churn from Kaggle, or your own dataset). Just edit the CONFIG section below.

Steps this script performs:
  1. Load the CSV
  2. Basic cleaning (drop ID columns, fix bad numeric columns, drop/fill NaNs)
  3. Encode the target column and categorical features
  4. Train/test split + scaling
  5. Train Logistic Regression and KNN
  6. Compare accuracy, confusion matrices, feature weights
  7. Test multiple k values for KNN
  8. Save result charts
"""

# Create a dummy data.csv file for demonstration purposes
data = {
    'customerID': [f'C{i:04d}' for i in range(100)],
    'gender': np.random.choice(['Male', 'Female'], 100),
    'SeniorCitizen': np.random.choice([0, 1], 100),
    'Partner': np.random.choice(['Yes', 'No'], 100),
    'Dependents': np.random.choice(['Yes', 'No'], 100),
    'tenure': np.random.randint(1, 72, 100),
    'PhoneService': np.random.choice(['Yes', 'No'], 100),
    'MultipleLines': np.random.choice(['No', 'Yes', 'No phone service'], 100),
    'InternetService': np.random.choice(['DSL', 'Fiber optic', 'No'], 100),
    'OnlineSecurity': np.random.choice(['No', 'Yes', 'No internet service'], 100),
    'OnlineBackup': np.random.choice(['No', 'Yes', 'No internet service'], 100),
    'DeviceProtection': np.random.choice(['No', 'Yes', 'No internet service'], 100),
    'TechSupport': np.random.choice(['No', 'Yes', 'No internet service'], 100),
    'StreamingTV': np.random.choice(['No', 'Yes', 'No internet service'], 100),
    'StreamingMovies': np.random.choice(['No', 'Yes', 'No internet service'], 100),
    'Contract': np.random.choice(['Month-to-month', 'One year', 'Two year'], 100),
    'PaperlessBilling': np.random.choice(['Yes', 'No'], 100),
    'PaymentMethod': np.random.choice(['Electronic check', 'Mailed check', 'Bank transfer (automatic)', 'Credit card (automatic)'], 100),
    'MonthlyCharges': np.random.uniform(20, 110, 100),
    'TotalCharges': np.random.uniform(20, 7000, 100),
    'Churn': np.random.choice(['Yes', 'No'], 100, p=[0.25, 0.75])
}
df_dummy = pd.DataFrame(data)
df_dummy.to_csv('data.csv', index=False)
print("Created a dummy 'data.csv' file.")

"""Now that a dummy `data.csv` file has been created, please run the main script cell (`a059a190`) again.

If you want to use your own dataset, you can either:
1. Upload your CSV file and name it `data.csv` (this will overwrite the dummy file).
2. Change the `CSV_PATH` variable in the `CONFIG` section of the main script (`a059a190`) to the name/path of your own CSV file.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# ==================================================================
# CONFIG — edit these for your dataset
# ==================================================================
CSV_PATH = "data.csv"          # path to your dataset
TARGET_COLUMN = "Churn"        # the column you're trying to predict
DROP_COLUMNS = ["customerID"]  # ID or irrelevant columns to remove
POSITIVE_LABEL = "Yes"         # value in target column meaning class = 1
NEGATIVE_LABEL = "No"          # value in target column meaning class = 0
# ==================================================================


def load_and_clean_data(csv_path, target_col, drop_cols, pos_label, neg_label):
    df = pd.read_csv(csv_path)
    print(f"Loaded dataset: {df.shape[0]} rows, {df.shape[1]} columns")

    # Drop irrelevant columns if present
    existing_drops = [c for c in drop_cols if c in df.columns]
    if existing_drops:
        df = df.drop(columns=existing_drops)

    # Try converting any non-numeric columns that are actually numeric
    # (common issue: numeric columns stored as strings with blanks)
    for col in df.columns:
        if not pd.api.types.is_numeric_dtype(df[col]) and col != target_col:
            converted = pd.to_numeric(df[col], errors="coerce")
            # only replace if most values converted successfully
            if converted.notna().sum() > 0.9 * len(df):
                df[col] = converted

    # Drop rows with missing values (simple approach)
    before = len(df)
    df = df.dropna()
    after = len(df)
    if before != after:
        print(f"Dropped {before - after} rows with missing values")

    # Encode target column if it's text
    if not pd.api.types.is_numeric_dtype(df[target_col]):
        df[target_col] = df[target_col].map({pos_label: 1, neg_label: 0})
        df = df.dropna(subset=[target_col])
        df[target_col] = df[target_col].astype(int)

    return df


def main():
    # ------------------------------------------------------------
    # 1. LOAD + CLEAN
    # ------------------------------------------------------------
    df = load_and_clean_data(
        CSV_PATH, TARGET_COLUMN, DROP_COLUMNS, POSITIVE_LABEL, NEGATIVE_LABEL
    )

    print("\nClass balance:")
    print(df[TARGET_COLUMN].value_counts())

    # ------------------------------------------------------------
    # 2. FEATURES / TARGET SPLIT + ENCODING
    # ------------------------------------------------------------
    X = df.drop(columns=[TARGET_COLUMN])
    y = df[TARGET_COLUMN]

    # One-hot encode any remaining categorical (text) columns
    X = pd.get_dummies(X, drop_first=True)

    print(f"\nFinal feature count after encoding: {X.shape[1]}")

    # ------------------------------------------------------------
    # 3. TRAIN/TEST SPLIT + SCALING
    # ------------------------------------------------------------
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # ------------------------------------------------------------
    # 4. TRAIN MODELS
    # ------------------------------------------------------------
    log_reg = LogisticRegression(max_iter=2000)
    log_reg.fit(X_train_scaled, y_train)
    log_reg_preds = log_reg.predict(X_test_scaled)

    knn = KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_train_scaled, y_train)
    knn_preds = knn.predict(X_test_scaled)

    # ------------------------------------------------------------
    # 5. COMPARE RESULTS
    # ------------------------------------------------------------
    log_reg_acc = accuracy_score(y_test, log_reg_preds)
    knn_acc = accuracy_score(y_test, knn_preds)

    print("\n" + "=" * 50)
    print(f"Logistic Regression Accuracy: {log_reg_acc:.3f}")
    print(f"KNN (k=5) Accuracy:           {knn_acc:.3f}")
    print("=" * 50)

    print("\nLogistic Regression Confusion Matrix:")
    print(confusion_matrix(y_test, log_reg_preds))
    print("\nLogistic Regression Classification Report:")
    print(classification_report(y_test, log_reg_preds, zero_division=0))

    print("\nKNN Confusion Matrix:")
    print(confusion_matrix(y_test, knn_preds))
    print("\nKNN Classification Report:")
    print(classification_report(y_test, knn_preds, zero_division=0))

    # Top feature weights (Logistic Regression)
    print("\nTop 10 most influential features (by |coefficient|):")
    coef_df = pd.DataFrame({
        "feature": X.columns,
        "weight": log_reg.coef_[0]
    }).sort_values("weight", key=abs, ascending=False)
    print(coef_df.head(10).to_string(index=False))

    # ------------------------------------------------------------
    # 6. TRY DIFFERENT K VALUES
    # ------------------------------------------------------------
    print("\nKNN accuracy across different k values:")
    k_values = [1, 3, 5, 9, 15, 25, 35]
    knn_scores = []
    for k in k_values:
        knn_k = KNeighborsClassifier(n_neighbors=k)
        knn_k.fit(X_train_scaled, y_train)
        acc = knn_k.score(X_test_scaled, y_test)
        knn_scores.append(acc)
        print(f"  k={k}: accuracy={acc:.3f}")

    # ------------------------------------------------------------
    # 7. VISUALIZATIONS
    # ------------------------------------------------------------
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    # Plot 1: KNN accuracy vs k
    axes[0].plot(k_values, knn_scores, marker="o")
    axes[0].axhline(log_reg_acc, color="red", linestyle="--", label="Logistic Regression")
    axes[0].set_xlabel("k (number of neighbors)")
    axes[0].set_ylabel("Accuracy")
    axes[0].set_title("KNN Accuracy vs k")
    axes[0].legend()

    # Plot 2: Top feature weights bar chart
    top_features = coef_df.head(10)
    colors = ["crimson" if w < 0 else "steelblue" for w in top_features["weight"]]
    axes[1].barh(top_features["feature"], top_features["weight"], color=colors)
    axes[1].set_xlabel("Coefficient weight")
    axes[1].set_title("Top 10 Logistic Regression Feature Weights")
    axes[1].invert_yaxis()

    plt.tight_layout()
    plt.savefig("classification_results.png", dpi=120)
    print("\nSaved chart to classification_results.png")

    # ------------------------------------------------------------
    # 8. YOUR TASK
    # ------------------------------------------------------------
    # 1. Which model won on accuracy, and by how much?
    # 2. Which k value gave the best KNN performance?
    # 3. Which features had the strongest positive/negative influence?
    # 4. Look at precision/recall in the classification_report — is the
    #    model better at catching positives or negatives? Why might that
    #    matter for this specific problem (e.g. churn = missed customers
    #    you should have retained)?


if __name__ == "__main__":
    main()

"""Please run the code above to generate the classification results. After execution, you can analyze the output in the console and the generated `classification_results.png` file to answer the questions posed in the comments at the end of the script."""