# -*- coding: utf-8 -*-
"""DAY-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vwx-VS6YnA9KQoOTeVuE31QoRonijXbJ
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

"""for multiple linear regresion model y mx1+mx2+mxn+C"""

df = pd.read_csv('/content/archive (1).zip')

df.info()

df.head(10)

df.shape

df.describe()

#df.duplicated().sum()

df.isnull().sum()

X=df.iloc[:,:3]

y=df.iloc[:,-1]

X

#making object of linear model
data=LinearRegression()

#how much we expense in the newspaper TV and radio

expenditure=[df['Newspaper'].sum(),df['Radio'].sum(),df['TV'].sum()]

labels=['Newspaper','Radio','TV']
plt.bar(labels,expenditure,color='g',label='compare the different type of mode ')
plt.show()

expenditure

sns.scatterplot(x='TV',y='Sales',data=df)

sns.scatterplot(x='TV',y='Radio',data=df,hue='Sales')

gf=sns.scatterplot(x='TV',y='Sales',data=df)
dg=sns.scatterplot(x='Radio',y='Sales',data=df)
my=sns.scatterplot(x='Newspaper',y='Sales',data=df)

dg

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#train the model
data.fit(X_train, y_train)

plt.scatter(X_train,y_train)
plt.plot(X_train,y_pred,color='r')
plt.show()



from sklearn.metrics import mean_squared_error ,r2_score

# making predictions on the test set
y_pred = data.predict(X_test)

# check mean squared error
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("MSE:", mse)
print("R²:", r2)

