# -*- coding: utf-8 -*-
"""superresolution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrCthVfC7Pk5N0P1x0Tz39f4d47onih2
"""

import argparse
import os
import urllib.request
import cv2
import numpy as np
import matplotlib.pyplot as plt

model_url = "https://github.com/Saafke/FSRCNN_Tensorflow/raw/master/models/FSRCNN_x4.pb"
model_path = "FSRCNN_x4.pb"
sample_image_url = "https://www.nasa.gov/sites/default/files/thumbnails/image/main_image_deep_field_smacs0723-5mb.jpg" # Original URL, but will be bypassed
sample_image_path = "sample_highres.jpg"

def load_sr_model():
  if not os.path.exists(model_path):
    print("downloading pretrained fsrcnn model...")
    urllib.request.urlretrieve(model_url, model_path)
  sr = cv2.dnn_superres.DnnSuperResImpl_create() # Corrected: using DnnSuperResImpl_create() constructor
  sr.readModel(model_path) # Corrected: 'readmodel' to 'readModel'
  sr.setModel("fsrcnn", 4) # Corrected: 'setmodel' to 'setModel'
  print("super resolution model loaded")
  return sr

def get_sample_low_res_image():
  if not os.path.exists(sample_image_path):
    print("URL download bypassed or failed. Creating a dummy high-resolution image locally.")
    # Create a simple white image 800x600 for demonstration
    dummy_img = np.full((600, 800, 3), 255, dtype=np.uint8)
    cv2.imwrite(sample_image_path, dummy_img)
  # Original download logic commented out to bypass URL error:
  # if not os.path.exists(sample_image_path):
  #   print("downloading sample high resolution photo")
  #   urllib.request.urlretrieve(sample_image_url, sample_image_path)
  high_res_ground_truth = cv2.imread(sample_image_path)
  high_res_ground_truth = cv2.resize(high_res_ground_truth, (800, 600))
  low_res = cv2.resize(high_res_ground_truth, (200, 150), interpolation=cv2.INTER_CUBIC)
  low_res_path = "simulated_low_res.png"
  cv2.imwrite(low_res_path, low_res)
  return low_res_path, high_res_ground_truth

def center_crop(img, size=200):
  h, w = img.shape[:2]
  cy, cx = h // 2, w // 2
  half = size // 2
  return img[max(cy - half, 0):cy + half, max(cx - half, 0):cx + half]

def to_rgb(img):
  return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

def save_comparison_gallery(low_res_img, bicubic_upscaled, ai_upscaled, out_path="comparison_gallery.png"):
  fig, axes = plt.subplots(2, 2, figsize=(14, 12))
  axes[0, 0].imshow(to_rgb(low_res_img))
  axes[0, 0].set_title(f"low-res input({low_res_img.shape[1]}x{low_res_img.shape[0]})")
  axes[0, 0].axis("off")
  axes[0, 1].imshow(to_rgb(ai_upscaled))
  axes[0, 1].set_title("ai super resolution full")
  axes[0, 1].axis("off")
  axes[1, 0].imshow(to_rgb(center_crop(bicubic_upscaled)))
  axes[1, 0].set_title("bicubic (zoomed) - blurry, no new detail")
  axes[1, 0].axis("off")
  axes[1, 1].imshow(to_rgb(center_crop(ai_upscaled)))
  axes[1, 1].set_title("ai super resolution (zoomed) - reconstructed detail")
  axes[1, 1].axis("off")
  plt.tight_layout()
  plt.savefig(out_path, dpi=150)
  plt.close()
  print(f"saved: {out_path}")

def main(image_path=None):
  sr = load_sr_model()
  ground_truth = None
  if image_path is None:
    print("no image provided - using an auto downloaded sample instead")
    image_path, ground_truth = get_sample_low_res_image()

  low_res_img = cv2.imread(image_path)
  if low_res_img is None:
    raise FileNotFoundError(f"could not read image: {image_path}")

  ai_upscaled = sr.upsample(low_res_img)
  target_h, target_w = ai_upscaled.shape[:2]
  bicubic_upscaled = cv2.resize(low_res_img, (target_w, target_h), interpolation=cv2.INTER_CUBIC)

  print(f"low-res input: {low_res_img.shape[1]}x{low_res_img.shape[0]}")
  print(f"upscaled output: {target_w}x{target_h} (4x)")

  if ground_truth is not None:
    gt_resized = cv2.resize(ground_truth, (target_w, target_h))
    psnr_bicubic = cv2.PSNR(gt_resized, bicubic_upscaled)
    psnr_ai = cv2.PSNR(gt_resized, ai_upscaled)
    print(f"psnr vs original --- bicubic: {psnr_bicubic:.2f}db | ai super resolution: {psnr_ai:.2f}db")
    print("(higher psnr = closer to the true high resolution image)")
    cv2.imwrite("ai_upscaled_result.png", ai_upscaled)
    cv2.imwrite("bicubic_upscaled_result.png", bicubic_upscaled)
    print("saved: ai_upscaled_result.png, bicubic_upscaled_result.png")
    save_comparison_gallery(low_res_img, bicubic_upscaled, ai_upscaled)
    print("done")

if __name__ == "__main__":
  parser = argparse.ArgumentParser(description="ai image super resolution vs bicubic upscalling")
  parser.add_argument("--image", default=None, help="path to a low resolution image. if omitted, a sample is auto-downloaded")
  # In a notebook environment, argparse tries to parse arguments like -f, which are passed by the kernel.
  # To prevent this, we explicitly pass an empty list for args.
  args = parser.parse_args([])
  main(image_path=args.image)

"""### Using Your Own Local Image

To use your own local image, upload it to your Colab environment. For example, if you upload an image named `my_image.jpg`, you can then call the `main` function with its path:
"""

# Replace 'my_image.jpg' with the actual path to your uploaded image file
# For example, if you upload it to the root of your Colab workspace, it would be '/content/my_image.jpg'
custom_image_path = '/content/images.jpg'

# Call the main function with your custom image path
main(image_path=custom_image_path)

from IPython.display import Image
Image('ai_upscaled_result.png')

from IPython.display import Image
Image('comparison_gallery.png')

print(dir(cv2.dnn_superres))

print(f"Model URL: {model_url}")
print(f"Sample Image URL: {sample_image_url}")

"""### Fix Numpy ABI Mismatch

The `RuntimeError` you encountered is due to an Application Binary Interface (ABI) mismatch between the `opencv-contrib-python` library and the currently installed `numpy` version.

`opencv-contrib-python==4.5.5.64` was compiled against `numpy` ABI `0x1000009`, but your current `numpy` (version 2.0.2) uses ABI `0x2000000`.

To resolve this, we need to downgrade `numpy` to a compatible version, such as `1.23.5`.
"""

# Uninstall the current numpy version
!pip uninstall -y numpy

# Install a numpy version compatible with opencv-contrib-python==4.5.5.64
# numpy==1.26.4 is the last 1.x series release with pre-built wheels for Python 3.12 and compatible ABI.
!pip install numpy==1.26.4

# IMPORTANT: After running this cell, you MUST restart the Colab runtime
# (Runtime -> Restart runtime) and then re-run all cells to apply the changes
# and correctly load the compatible numpy version with OpenCV.

"""### Reinstall `opencv-contrib-python` after `numpy` downgrade

Even after downgrading `numpy`, the `AttributeError` on `cv2.dnn_superres` indicates that the `opencv-contrib-python` module may not have correctly re-linked with the new `numpy` version. To fix this, we need to reinstall `opencv-contrib-python==4.5.5.64` so it can properly build/configure itself against the `numpy==1.26.4` version.

**Crucially, after this cell runs, you will need to restart the runtime again.**
"""

# Reinstall opencv-contrib-python to ensure it links correctly with numpy 1.26.4
!pip install --upgrade --force-reinstall opencv-contrib-python==4.5.5.64

# IMPORTANT: After running this cell, you MUST restart the Colab runtime
# (Runtime -> Restart runtime) and then re-run all cells to apply the changes
# and correctly load the compatible numpy and OpenCV versions.

"""### Fixing `opencv-contrib-python` incompatibility with Python 3.12

The `AttributeError: module 'cv2' has no attribute 'dnn_superres'` persists because `opencv-contrib-python==4.5.5.64` is compiled for Python 3.6 ABI (`cp36-abi3`), which is incompatible with the current Colab Python 3.12 runtime (`cp312`). This prevents its modules from loading correctly.

To fix this, we will:
1.  Uninstall all existing `opencv-contrib-python` and `numpy` packages.
2.  Install the **latest** `opencv-contrib-python` version. This will ensure compatibility with Python 3.12 and install a corresponding compatible `numpy` 2.x version.
3.  After this installation, a **runtime restart is critical** to ensure the newly installed packages are loaded properly.
"""

# 1. Uninstall any existing opencv and numpy installations
!pip uninstall -y opencv-contrib-python opencv-python numpy

# 2. Install the latest opencv-contrib-python (compatible with Python 3.12)
# This will automatically pull in a compatible numpy 2.x version.
!pip install opencv-contrib-python

# IMPORTANT: After running this cell, you MUST restart the Colab runtime
# (Runtime -> Restart runtime) and then re-run all cells from the beginning.
# This will ensure the compatible OpenCV and numpy versions are loaded.

"""#### Final Attempt to Fix `opencv-contrib-python` Incompatibility

The `AttributeError` for `DnnSuperRes` persists because previous installations of `opencv-contrib-python` likely installed wheels (pre-compiled packages) that were built for older Python versions (e.g., `cp37-abi3` for Python 3.7), making them incompatible with the current Colab Python 3.12 runtime.

This cell performs a more aggressive cleanup and attempts to install the *latest possible* `opencv-contrib-python` version. It also includes `opencv-python-headless` in the uninstall list as it's another common variant that can cause conflicts.

**If, after running this cell and restarting the runtime, the `AttributeError` still occurs, it strongly suggests that an officially distributed `opencv-contrib-python` wheel with the `dnn_superres` module fully compatible with Python 3.12 is not yet available on PyPI. In such a scenario, you might need to wait for a future release or consider more advanced options like building OpenCV from source.**
"""

# 1. Force uninstall all known conflicting OpenCV and NumPy packages for a clean slate.
# This includes `opencv-python-headless` to cover more variants.
!pip uninstall -y opencv-contrib-python opencv-python opencv-python-headless numpy

# 2. Install the latest `opencv-contrib-python`.
# We hope that pip will now find and install a Python 3.12 (cp312) compatible wheel if one exists.
# This version should include the `dnn_superres` module with the `DnnSuperRes` class.
!pip install opencv-contrib-python

# IMPORTANT: After running this cell, you MUST restart the Colab runtime
# (Runtime -> Restart runtime) and then re-run all cells from the beginning.
# This step is crucial for the newly installed packages to be properly loaded.

import cv2

print(f"cv2 version: {cv2.__version__}")

if hasattr(cv2, 'dnn_superres'):
    print("cv2.dnn_superres module is available.")
    if hasattr(cv2.dnn_superres, 'DnnSuperResImpl'):
        print("cv2.dnn_superres.DnnSuperResImpl is available.")
    else:
        print("cv2.dnn_superres.DnnSuperResImpl is NOT available.")

    if hasattr(cv2.dnn_superres, 'DnnSuperRes'):
        print("cv2.dnn_superres.DnnSuperRes is available.")
    else:
        print("cv2.dnn_superres.DnnSuperRes is NOT available.")
else:
    print("cv2.dnn_superres module is NOT available. Please ensure opencv-contrib-python is installed and runtime is restarted.")

# Force uninstall current opencv-contrib-python and install a known stable version.
# This ensures the dnn_superres module with DnnSuperResImpl/DnnSuperRes classes is properly available.
!pip uninstall -y opencv-contrib-python
!pip install opencv-contrib-python==4.5.5.64

# IMPORTANT: After running this cell, you MUST restart the Colab runtime (Runtime -> Restart runtime)
# and then re-run all cells to apply the changes.

"""This code checks for the presence of the `dnn_superres` module and then specifically looks for `DnnSuperResImpl` and `DnnSuperRes` classes within it. The output will tell us which, if any, are detected in your current Python environment."""

# Install opencv-contrib-python to ensure dnn_superres module is available
!pip install opencv-contrib-python

# Note: After running this cell, you might need to restart the runtime (Runtime -> Restart runtime)
# and then re-run all cells to ensure the newly installed package is loaded correctly.

(800)